### ISSUE TITLE
[META] Performance Improvements

### ISSUE THREAD

**Issue by nixpulvis** [nixpulvis/dinosaurcowboys#117]
It's time to save time. Speed things up in the realm of postgres. Be it caching values, better indices, or even just removing things. Lets attack the bottlenecks.

- [x] #123 - Optimize `last_post`.
- [x] #135 - Counter Cache Things.
- [ ] #143 - Cache View Counts.
- [ ] #122 - Make Permissions Polymorphic
- [ ] #144 - Optimize Post `page` Method.
