### ISSUE TITLE
[META] Design Fixes and Changes

### ISSUE THREAD

**Issue by nixpulvis** [nixpulvis/dinosaurcowboys#126]
This is the meta bug for all of the design cleanups we want to do with the site.

- [ ] #60 - Photo Slider.
- [ ] #132 - Incorporate UI Framework.
- [ ] #127 - Better Navigation Bar.
- [ ] #133 - Redesign Shoutbox Under UI Framework.
- [ ] #141 - Remove All Styles on Base Tags.
